services:
  db:
    image: mariadb:11
    container_name: clockingo-db
    env_file:
      - ../.env.docker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 --protocol=TCP -uroot -p\"${MARIADB_ROOT_PASSWORD:-root}\" >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 30s

  api:
    build:
      context: ..
      dockerfile: server/Dockerfile
      target: prod
    container_name: clockingo-api
    env_file:
      - ../.env.docker
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --header='x-api-key: ${API_KEY}' -qO- http://localhost:3000/health | grep -q '\"ok\":true'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  db_data: